name: Build and Deploy to Cloud Function

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: asia-southeast1
  GKE_CLUSTER: ique-app  
  GKE_ZONE: asia-southeast1-a  
  DEPLOYMENT_NAME: ique-sms
  REPOSITORY: ique-star6ucks
  IMAGE: ique-sms

jobs:
  setup-build-publish-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'deploy generate-report'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'generate-report'
        runtime: 'python3.10'
        entry_point: 'generate_report'
        
    - id: 'deploy get-reports'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'get-reports'
        runtime: 'python3.10'
        entry_point: 'generate_report'
