name: Build and Deploy to Cloud Function

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  DB_MYSQL_NAME: ${{ secrets.DB_MYSQL_NAME }}
  DB_MYSQL_PASS: ${{ secrets.DB_MYSQL_PASS }}
  DB_MYSQL_UNIX_SOCKET: ${{ secrets.DB_MYSQL_UNIX_SOCKET }}
  DB_MYSQL_USER: ${{ secrets.DB_MYSQL_USER }}
  DB_PG_NAME: ${{ secrets.DB_PG_NAME }}
  DB_PG_PASS: ${{ secrets.DB_PG_PASS }}
  DB_PG_UNIX_SOCKET: ${{ secrets.DB_PG_UNIX_SOCKET }}
  DB_PG_USER: ${{ secrets.DB_PG_USER }}
  
jobs:
  setup-build-publish-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      

    - id: 'deploy-generate-report'
      run: 'gcloud functions deploy generate-report --gen2 --runtime=python310 --region=asia-southeast1 --source=. --entry-point=generate_report --trigger-http --allow-unauthenticated --set-env-vars DB_MYSQL_NAME=$DB_MYSQL_NAME,DB_MYSQL_PASS=$DB_MYSQL_PASS,DB_MYSQL_UNIX_SOCKET=$DB_MYSQL_UNIX_SOCKET,DB_MYSQL_USER=$DB_MYSQL_USER,DB_PG_NAME=$DB_PG_NAME,DB_PG_PASS=$DB_PG_PASS,DB_PG_UNIX_SOCKET=$DB_PG_UNIX_SOCKET,DB_PG_USER=$DB_PG_USER'
        
    - id: 'deploy-get-reports'
      run: 'gcloud functions deploy get-reports --gen2 --runtime=python310 --region=asia-southeast1 --source=. --entry-point=get_reports --trigger-http --allow-unauthenticated --set-env-vars DB_MYSQL_NAME=$DB_MYSQL_NAME,DB_MYSQL_PASS=$DB_MYSQL_PASS,DB_MYSQL_UNIX_SOCKET=$DB_MYSQL_UNIX_SOCKET,DB_MYSQL_USER=$DB_MYSQL_USER,DB_PG_NAME=$DB_PG_NAME,DB_PG_PASS=$DB_PG_PASS,DB_PG_UNIX_SOCKET=$DB_PG_UNIX_SOCKET,DB_PG_USER=$DB_PG_USER'


